
//#define NEW_PROTOCOL_SYSTEM

#define LEM_ADD_LUCKYITEM
#define PBG_ADD_NEWCHAR_MONK
#define PBG_ADD_NEWCHAR_MONK_ITEM
#define PBG_ADD_NEWCHAR_MONK_ANI
#define PBG_ADD_NEWCHAR_MONK_SKILL
#define PBG_MOD_RAGEFIGHTERSOUND

#define LJH_ADD_SYSTEM_OF_EQUIPPING_ITEM_FROM_INVENTORY
#define LJH_ADD_ITEMS_EQUIPPED_FROM_INVENTORY_SYSTEM
#define LJH_ADD_ITEMS_EQUIPPED_FROM_INVENTORY_SYSTEM_PART_2

#define ASG_ADD_MAP_KARUTAN
#define ASG_ADD_KARUTAN_NPC
#define ASG_ADD_KARUTAN_MONSTERS


//==Test
#define LJW_FIX_MANY_FLAG_DISAPPEARED_PROBREM
#define PARTS_NONE                          0x0
#define DEBUG									1

#if (DEBUG==1)
#define ENABLE_EDIT
#define ENABLE_EDIT2
//#define DEBUG_BITMAP_CACHE
#endif // _DEBUG

#ifdef FOR_WORK
#if (DEBUG==0)

#define CSK_LH_DEBUG_CONSOLE
#ifdef CSK_LH_DEBUG_CONSOLE
#define CONSOLE_DEBUG	
#endif // CSK_LH_DEBUG_CONSOLE

#define CSK_DEBUG_MAP_ATTRIBUTE

#define CSK_DEBUG_RENDER_BOUNDINGBOX

#define CSK_DEBUG_MAP_PATHFINDING

#endif // _DEBUG
#endif // FOR_WORK
//==========
#define PJH_NEW_SERVER_SELECT_MAP

#define ASG_ADD_GENS_SYSTEM
#ifdef ASG_ADD_GENS_SYSTEM
	#define ASG_ADD_INFLUENCE_GROUND_EFFECT
	#define ASG_ADD_GENS_MARK
	#define PBG_MOD_STRIFE_GENSMARKRENDER
	#define PBG_ADD_GENSRANKING
#endif	// ASG_ADD_GENS_SYSTEM

#define KJH_PBG_ADD_INGAMESHOP_SYSTEM
#ifdef KJH_PBG_ADD_INGAMESHOP_SYSTEM
	#define PBG_ADD_INGAMESHOP_UI_MAINFRAME
	#define PBG_ADD_INGAMESHOP_UI_ITEMSHOP
	#define PBG_ADD_NAMETOPMSGBOX
	#define KJH_ADD_INGAMESHOP_UI_SYSTEM
	#define KJH_ADD_PERIOD_ITEM_SYSTEM
	#define PBG_ADD_INGAMESHOPMSGBOX
	#define PBG_ADD_ITEMRESIZE
	#define KJH_MOD_SHOP_SCRIPT_DOWNLOAD
	//^#define PBG_ADD_CHARACTERSLOT
	#define PBG_ADD_CHARACTERCARD
	//^#define LDK_ADD_INGAMESHOP_LIMIT_MOVE_WINDOW
#endif //KJH_PBG_ADD_INGAMESHOP_SYSTEM

#define PJH_ADD_PANDA_PET
#define PJH_ADD_PANDA_CHANGERING

#define ASG_ADD_TIME_LIMIT_QUEST_NPC



//#define  LOGO_LOADING_SCREEN
#define NEM_ADD_NEW_TYPE_OF_SEPARATOR_FINAL				// Add: "SeparatorFinal()" procedure to: "MuError.log" File Write-Event Final of Session (2021.10.08)
